version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile_app
    container_name: similarity-flask
    volumes:
      - compare_results:/app/static/compare_results/
      - ${IMAGES_PATH}:/app/static/images/
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2048M
        reservations:
          cpus: '0.2'
          memory: 1024M
    restart: always
    ports:
      - "8080:8080"
    networks:
      - scrapy
    env_file: .env

networks:
  scrapy:
    name: ${NETWORK_NAME}
    external: true

volumes:
  compare_results: